version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cmake -B build
     - cmake --build build --config Release
     - cp ./build/Release/example.exe .
     - cp ./build/mathlib_build/Release/mathlib.dll .
     - ./example.exe

  clear:
    aliases: ["c"]
    cmds:
     - rm -rf build