version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cp ../A_mathlib/example/mathlib.dll ./lib
     - zig build run

  clean:
    aliases: ["c"]
    cmds:
     - rm -rf .zig-cache
     - rm -rf zig-out