version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
    # build mathlib
     - cd ../A_mathlib && task
    # copy dependencies
     - cp ../A_mathlib/build/Debug/mathlib.dll ./lib
    # build zig project
     - zig build run

  clean:
    aliases: ["c"]
    cmds:
     - rm -rf .zig-cache
     - rm -rf zig-out