version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cmake -B build
     - cmake --build build
     - cp build/example/Debug/example.exe a_output
     - cp build/mathlib/Debug/mathlib.dll a_output
     - cp ziglib/zigmath.dll a_output
     - ./a_output/example.exe