version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
    # run zig build
     - cd B_zig_code && zig build
    # copy zigmath to `ziglib` folder
     - mkdir -p ziglib
     - cp B_zig_code/zig-out/bin/zigmath.dll ziglib
     - cp B_zig_code/zig-out/lib/zigmath.lib ziglib
    # building project
     - cmake -B build
     - cmake --build build
    # copying executable and dependencies to `z_output`
     - mkdir -p build/z_output
     - cp build/A_mathlib/Debug/mathlib.dll build/z_output
     - cp build/C_c_example/Debug/example.exe build/z_output
     - cp build/C_c_example/Debug/example.exe build/z_output
     - cp ziglib/zigmath.dll build/z_output
    # running example.exe
     - ./build/z_output/example.exe

  clean:
    aliases: ["c"]
    cmds:
     - rm -rf build
     - rm -rf ziglib
     
  clean_all:
    aliases: ["call"]
    cmds:
     - cd A_mathlib/ && task clean
     - cd A_mathlib/example/ && task clean
     - cd B_zig_code/ && task clean
     - cd C_c_example/ && task clean
     - task clean
     
  run_a:
    cmds:
     - cd A_mathlib/example/ && task

  run_b:
    cmds:
     - cd B_zig_code/ && task
     
  run_c:
    cmds:
     - task