version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cmake -B build
     - cmake --build build
     - mkdir -p build/z_output
     - cp build/A_mathlib/Debug/mathlib.dll build/z_output
     - cp build/C_c_example/Debug/example.exe build/z_output
     - cp ziglib/zigmath.dll build/z_output
     - ./build/z_output/example.exe

  clean:
    aliases: ["c"]
    cmds:
     - rm -rf build

  folder:
    aliases: ["f"]
    cmds:
     - mkdir -p ff_bla
     - touch ff_bla/bla.txt