version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
    # building project
     - cmake -B build
     - cmake --build build --config Release
    # creating build/z_output dir
     - mkdir -p build/z_output
    # copying dll to target directory
     - cp ./build/mathlib_build/Release/mathlib.dll ./build/z_output/
     - cp ./build/Release/example.exe ./build/z_output/
    # running application
     - ./build/z_output/example.exe

  clean:
    aliases: ["c"]
    cmds:
     - rm -rf build